import { Project } from './types';

export const projects: Project[] = [
  {
    id: 'sonix-music',
    name: 'Sonix Music',
    subtitle: 'Full-Stack AI-Powered Streaming Platform',
    description:
      'A production-grade music streaming platform featuring Node.js & TypeScript REST APIs, AWS cloud architecture, BullMQ job queues, and an autonomous LangGraph + Gemini 3.1 AI agent microservice with pgvector RAG for personalized recommendations.',
    tech: [
      'TypeScript',
      'Node.js',
      'React',
      'Python',
      'FastAPI',
      'LangGraph',
      'Gemini 3.1',
      'pgvector',
      'PostgreSQL',
      'Redis',
      'BullMQ',
      'Docker',
      'AWS EC2',
      'AWS S3',
      'AWS RDS',
      'CloudFront',
      'GitHub Actions',
    ],
    liveUrl: 'https://sonix.saurabhx.site',
    githubUrl: 'https://github.com/Saurabh-singhx/sonix_music_app',
    status: 'Live',
    type: 'Full-Stack & GenAI Platform',
    icon: 'music',
    iconColor: '#00d2ff',
    metrics: [
      'Load-tested to 200–500 concurrent users on a single AWS t3.micro using k6',
      'High-throughput Redis caching with BullMQ async background worker queues',
      'Sub-second RAG search via pgvector vector embeddings on Supabase PostgreSQL',
    ],
    highlights: [
      'Built a production music streaming platform with Node.js and TypeScript REST APIs, Redis caching, BullMQ job queues, Google OAuth + OTP auth, and AWS S3 presigned URLs.',
      'Dockerized microservices on AWS EC2 with automated GitHub Actions CI/CD pipelines, serving frontend assets via S3 + CloudFront CDN.',
      'Load-tested to 200-500 concurrent users on a single t3.micro instance using k6 without performance degradation.',
      'Architected a LangGraph AI agent microservice (Python/FastAPI) with Gemini 3.1 tool-calling and pgvector RAG pipeline for personalized music recommendations, integrated via async SQLAlchemy on Supabase PostgreSQL.',
    ],
    architecture: [
      'Frontend: React + Tailwind CSS with responsive audio player & waveform visualizer',
      'Backend: Node.js / Express REST API with TypeScript, BullMQ, Redis, and JWT/OAuth',
      'AI Microservice: Python / FastAPI + LangGraph + Gemini 3.1 + pgvector RAG',
      'DevOps: Docker, AWS EC2, S3, RDS, CloudFront CDN, GitHub Actions CI/CD',
    ],
  },
  {
    id: 'finassist',
    name: 'FinAssist',
    subtitle: 'AI Financial Assistant Telegram Bot',
    description:
      'An intelligent multi-agent financial assistant Telegram bot built with LangGraph, Gemini 3.1, pgvector RAG, multi-API financial market orchestration (Finnhub, FRED, SEC EDGAR), and Google Workspace integration via OAuth 2.0 PKCE.',
    tech: [
      'Python',
      'FastAPI',
      'LangGraph',
      'Gemini 3.1',
      'pgvector',
      'PostgreSQL',
      'SQLAlchemy',
      'APScheduler',
      'Google OAuth 2.0',
      'Finnhub API',
      'FRED API',
      'SEC EDGAR',
      'Telegram Bot API',
      'Render',
    ],
    liveUrl: 'https://t.me/finance_ai_assistant_1bot',
    githubUrl: 'https://github.com/Saurabh-singhx/finassistai-telegram-bot',
    status: 'Live',
    type: 'GenAI & Autonomous Agent',
    icon: 'brain',
    iconColor: '#00ff41',
    metrics: [
      'Multi-modal document RAG pipeline processing PDFs, images, and voice notes',
      'Real-time financial queries across 3 external financial data sources',
      'Automated daily market intelligence briefings scheduled via APScheduler',
    ],
    highlights: [
      'Built a LangGraph-powered Telegram AI agent with multi-tool calling across Finnhub (live market data), FRED (macro indicators), and SEC EDGAR filings; deployed as a signed FastAPI webhook on Render.',
      'Implemented automated personalized daily market briefings delivered to subscribers via APScheduler cron workflows.',
      'Implemented a document intelligence Retrieval-Augmented Generation (RAG) pipeline: Gemini 3.1 extracts and transcribes PDFs, balance sheets, images, and voice notes; chunked, embedded into pgvector vector database, and retrieved semantically.',
      'Integrated Google OAuth 2.0 (PKCE, state validation, refresh tokens) enabling direct Gmail retrieval and Google Calendar event creation from within Telegram.',
    ],
    architecture: [
      'Agent Framework: LangGraph state graph with conditional routing & fallback handlers',
      'LLM Engine: Gemini 3.1 with function/tool calling for market APIs & document Q&A',
      'Vector Store: pgvector with cosine similarity search & chunking heuristics',
      'Deployment: FastAPI webhook server hosted on Render with encrypted secrets',
    ],
  },
  {
    id: 'gyanodaya-school',
    name: 'Gyanodaya Public School',
    subtitle: 'Production Institutional Web Portal',
    description:
      'A modern, high-performance responsive web portal built with Next.js and Tailwind CSS for Gyanodaya Public School, delivered within a 1-month timeline with comprehensive SEO best practices, high Lighthouse scores, and custom domain deployment on Vercel.',
    tech: [
      'Next.js',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Framer Motion',
      'Vercel',
      'SEO Optimization',
    ],
    githubUrl: 'https://github.com/Saurabh-singhx',
    status: 'Live',
    type: 'Client Production Portal',
    icon: 'building',
    iconColor: '#ffbd2e',
    metrics: [
      'Delivered within strict 1-month timeline from concept to launch',
      '95+ Google Lighthouse scores across Performance, Accessibility, and SEO',
      '100% mobile-responsive across phones, tablets, and desktops',
    ],
    highlights: [
      'Designed and developed a responsive Next.js website for Gyanodaya Public School, Patna, meeting all institutional and stakeholder requirements.',
      'Implemented SEO best practices including structured JSON-LD schemas, dynamic OpenGraph meta tags, and optimized asset delivery.',
      'Deployed on Vercel with automated continuous deployment and custom domain configuration.',
    ],
    architecture: [
      'Framework: Next.js App Router with React Server Components for near-instant loads',
      'Styling: Tailwind CSS with responsive layout grids and accessible UI design',
      'Deployment: Vercel Edge Network with asset optimization and caching',
    ],
  },
];

export const techColors: Record<string, string> = {
  TypeScript: 'bg-blue-500/10 text-blue-400 border-blue-500/30',
  JavaScript: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
  Python: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
  Node: 'bg-green-500/10 text-green-400 border-green-500/30',
  'Node.js': 'bg-green-500/10 text-green-400 border-green-500/30',
  React: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
  'Next.js': 'bg-white/10 text-white border-white/30',
  FastAPI: 'bg-teal-500/10 text-teal-400 border-teal-500/30',
  LangGraph: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
  'Gemini 3.1': 'bg-indigo-500/10 text-indigo-400 border-indigo-500/30',
  pgvector: 'bg-sky-500/10 text-sky-400 border-sky-500/30',
  PostgreSQL: 'bg-blue-600/10 text-blue-400 border-blue-600/30',
  Redis: 'bg-red-500/10 text-red-400 border-red-500/30',
  BullMQ: 'bg-pink-500/10 text-pink-400 border-pink-500/30',
  Docker: 'bg-sky-500/10 text-sky-400 border-sky-500/30',
  'AWS EC2': 'bg-orange-500/10 text-orange-400 border-orange-500/30',
  'AWS S3': 'bg-amber-500/10 text-amber-400 border-amber-500/30',
  'AWS RDS': 'bg-blue-500/10 text-blue-400 border-blue-500/30',
  CloudFront: 'bg-violet-500/10 text-violet-400 border-violet-500/30',
  'GitHub Actions': 'bg-gray-500/10 text-gray-300 border-gray-500/30',
  Render: 'bg-cyan-600/10 text-cyan-300 border-cyan-600/30',
  SQLAlchemy: 'bg-red-600/10 text-red-400 border-red-600/30',
  'Tailwind CSS': 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
  Vercel: 'bg-neutral-200/10 text-white border-white/20',
};
